name: Build release apps
on:
  release:
    types: [published]

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Run code gen
        run: flutter pub run build_runner build --delete-conflicting-outputs

  build-android:
    runs-on: ubuntu-latest
    needs: pre-build
    steps:
      - name: Generate key
        run: |
          keytool -genkey -v -keystore ~/upload-keystore.jks -keyalg RSA 
                  -keysize 2048 -validity 10000 -alias upload

      - name: Build Android
        run: flutter build apk --release

      # - name: Upload APK artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: apk-app
      #     path: .

  build-web:
    runs-on: ubuntu-latest
    needs: pre-build
    steps:
      - name: Build web
        run: flutter build web -t lib/main.dart --release

      - name: Upload web artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-app
          path: build/web/

  build-ios:
    runs-on: macos-latest
    needs: pre-build
    steps:
      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: ipa-app
          path: build/ios/iphoneos/Runner.app

  # build-macos:
  #   runs-on: macos-latest
  #   needs: pre-build
  #   steps:
  #     - name: Build macOS
  #       run: flutter build macos --release

  #     - name: Upload DMG artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: dmg-app
  #         path: build/macos/Build/Products/Release/Runner.app

  # build-windows:
  #   runs-on: windows-latest
  #   needs: pre-build
  #   steps:
  #     - name: Build Windows
  #       run: flutter build windows --release

  #     - name: Upload ZIP artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: zip-app
  #         path: build/windows/runner/Release/
